// // import { Manufacturer } from "../types";

// let manufacturers: Manufacturer[] = [
//   {
//     Name: "Advance",
//     Wings: [
//       "Alpha",
//       "Beta",
//       "Epsilon",
//       "Iota",
//       "Omega",
//       "Omega Xalps",
//       "Omikron",
//       "Pi",
//       "Pi Bi",
//       "Sigma",
//       "Zeta",
//       "Xi",
//       "Bibeta"
//     ]
//   },
//   {
//     Name: "Air Design",
//     Wings: [
//       "Eazy",
//       "Fox",
//       "Hero",
//       "Hike",
//       "Pure",
//       "Pure Race",
//       "Rama",
//       "Ride",
//       "Rise",
//       "Susi",
//       "Ufo",
//       "Vita",
//       "Volt"
//     ]
//   },
//   {
//     Name: "AirCross",
//     Wings: [
//       "Artica",
//       "Catia",
//       "Pelerin",
//       "Tamalou",
//       "Trialp",
//       "U Cross",
//       "U Cruise",
//       "U Double",
//       "U Fly",
//       "U Infinite",
//       "Ultima",
//       "U Prime",
//       "U Share",
//       "U Sport",
//       "U Sport Evo",
//       "U Sport Fr"
//     ]
//   },
//   {
//     Name: "Airwave",
//     Wings: [
//       "Alpine",
//       "Alto",
//       "Alto Xm",
//       "Bi-Boo",
//       "Black Magic",
//       "Burn",
//       "Carve",
//       "Cobra",
//       "Combi",
//       "Duet",
//       "Duplex",
//       "Epic",
//       "Explorer",
//       "Flite",
//       "Fusion",
//       "Gecko ",
//       "Harmony",
//       "Jive",
//       "Kiss",
//       "Logic",
//       "Micro",
//       "Magic",
//       "Magic",
//       "Magic Fr",
//       "Mustang",
//       "Puma",
//       "Rave",
//       "Rave Race",
//       "Reggae",
//       "Rodeo",
//       "Samba",
//       "Scenic ",
//       "Skima",
//       "Slingshot",
//       "Sport",
//       "Stingray",
//       "Taboo",
//       "Tandem",
//       "Tango",
//       "Ten",
//       "Voodoo ",
//       "Wave",
//       "Xmx",
//       "Xxx"
//     ]
//   },
//   {
//     Name: "APCO",
//     Wings: [
//       "Airxtreme",
//       "Allegra",
//       "Allround",
//       "Alpin",
//       "Astra",
//       "Bagheera",
//       "Cruiser",
//       "Cz",
//       "Enigma",
//       "Fiesta",
//       "Fiesta Light",
//       "Force",
//       "Fun",
//       "Fun For 2",
//       "Futura",
//       "Futura Bi",
//       "Game",
//       "Hilite ",
//       "Hybrid",
//       "Karisma",
//       "Karma",
//       "Karma Evo",
//       "Karma Sport",
//       "Keara",
//       "Lambada",
//       "Libra",
//       "Lift",
//       "Lift Ez",
//       "Micro",
//       "Nrg",
//       "Nrg Pro",
//       "Play",
//       "Power Wing",
//       "Presta",
//       "Prima",
//       "Sabra",
//       "Salsa",
//       "Santana",
//       "Sentra",
//       "Sierra",
//       "Simba",
//       "Sk",
//       "Spectra",
//       "Speed Star",
//       "Starlite",
//       "Supra",
//       "Tetra",
//       "Thrust",
//       "Thrust Hp",
//       "Tigra",
//       "Twister",
//       "Vista",
//       "Vista",
//       "Vista Hp",
//       "Xtra",
//       "Zefira",
//       "Zen "
//     ]
//   },
//   {
//     Name: "Axis",
//     Wings: [
//       "Comet",
//       "Compact",
//       "Gigant",
//       "Mercury",
//       "Mercury Sport",
//       "Meteor",
//       "Neptun",
//       "Pluto",
//       "Polaris",
//       "Proton 2",
//       "Pulsar",
//       "Sirius 1",
//       "Vega",
//       "Vega Duo",
//       "Venus"
//     ]
//   },
//   {
//     Name: "Bruce Goldsmith Design",
//     Wings: [
//       "Adam",
//       "Base",
//       "Cure",
//       "Diva",
//       "Dual",
//       "Echo",
//       "Epic",
//       "Luna",
//       "Lynx",
//       "Punk",
//       "Seed",
//       "Tala",
//       "Wasp"
//     ]
//   },
//   {
//     Name: "Dudek",
//     Wings: [
//       "Action",
//       "Air Light",
//       "Alt",
//       "Atak",
//       "Boheme",
//       "Coden",
//       "Coden Pro",
//       "Colt",
//       "Condor",
//       "Dolphin",
//       "Elf",
//       "Freeway",
//       "Freeway Xx",
//       "Guliver",
//       "Hadron ",
//       "Hadron Xx",
//       "Jumbo",
//       "Lux",
//       "Mach",
//       "Manta",
//       "Marlin",
//       "Max",
//       "Nemo ",
//       "Nucleon",
//       "Nucleon Wrc",
//       "Nucleon Xx",
//       "Optic",
//       "Orca",
//       "Patrol",
//       "Plasma",
//       "Plus",
//       "Re Action",
//       "Report'air",
//       "Rex",
//       "Shark",
//       "Snake",
//       "Synthesis",
//       "Top",
//       "Universal",
//       "Vip",
//       "Vox",
//       "Wezyr",
//       "Zakospeed",
//       "Zig-Zag"
//     ]
//   },
//   {
//     Name: "FireBird",
//     Wings: [
//       "Albatros",
//       "Apache",
//       "Arobas",
//       "Barracuda",
//       "Booster",
//       "Choice",
//       "Cobra",
//       "Comanche",
//       "Condor",
//       "Cult",
//       "Dolphin",
//       "Debute",
//       "Eagle",
//       "Easy",
//       "Extase",
//       "F 1 C",
//       "F1rst",
//       "F 10",
//       "F 18",
//       "Flame",
//       "Fox",
//       "Grid",
//       "Genesis",
//       "G-Sport",
//       "Hornet",
//       "Hornet Sp",
//       "Hyper C",
//       "Ignition",
//       "Inspiration",
//       "Marlin",
//       "Matrix",
//       "Monster",
//       "Navajo",
//       "Ninja",
//       "N-Joy",
//       "Phoenix",
//       "Platoon",
//       "Raven",
//       "Rocket",
//       "Solo",
//       "Spider",
//       "Sub-One",
//       "Trainer",
//       "Tribute",
//       "Twist",
//       "Twix",
//       "X-3",
//       "Z-One"
//     ]
//   },
//   { Name: "Flow", Wings: [] },
//   { Name: "FreeX", Wings: [] },
//   { Name: "Gin", Wings: [] },
//   { Name: "Gradient", Wings: [] },
//   { Name: "Icaro", Wings: [] },
//   { Name: "independence", Wings: [] },
//   { Name: "ITV", Wings: [] },
//   { Name: "MacPara", Wings: [] },
//   { Name: "Nervures", Wings: [] },
//   { Name: "Niviuk", Wings: [] },
//   { Name: "Nova", Wings: [] },
//   { Name: "Ozone", Wings: [] },
//   { Name: "Paramania", Wings: [] },
//   { Name: "Paratech", Wings: [] },
//   { Name: "Pegas", Wings: [] },
//   { Name: "Phi", Wings: [] },
//   { Name: "Pro Design", Wings: [] },
//   { Name: "Sky", Wings: [] },
//   { Name: "Sky Country", Wings: [] },
//   { Name: "Skywalk", Wings: [] },
//   { Name: "Supair", Wings: [] },
//   { Name: "Sol", Wings: [] },
//   { Name: "Swing", Wings: [] },
//   { Name: "Team5", Wings: [] },
//   { Name: "Triple Seven", Wings: [] },
//   { Name: "UP", Wings: [] },
//   { Name: "U-turn", Wings: [] },
//   { Name: "Windtech", Wings: [] },
//   { Name: "Wings of Change", Wings: [] }
// ];
